[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/v1/*"
  to = "/.netlify/functions/api/v1/:splat"
  status = 200

[[redirects]]
  from = "/v1"
  to = "/.netlify/functions/api/v1"
  status = 200

[[redirects]]
  from = "/openapi.json"
  to = "/.netlify/functions/api/openapi.json"
  status = 200

[[redirects]]
  from = "/saude"
  to = "/.netlify/functions/api/saude"
  status = 200
